# Base Image
FROM node:21.7.0-bookworm-slim
WORKDIR /usr/src/app

# Install Dependencies
COPY package*.json ./
RUN npm install

# Copy in Application
COPY . .

# Set User to Non-Root
USER node

# Run Server
CMD [ "server.js" ]